# -*- coding: utf-8 -*-
{
    "name": "Contact Centre AI Copilot",
    "version": "18.0.1.0.0",
    "category": "Communications",
    "summary": "AI-generated conversation summary, sentiment, and suggested replies via Anthropic Claude",
    "description": """
Adds a per-contact AI summary, sentiment, and suggested reply, generated by
a cron job that calls the Anthropic Messages API. Requires an Anthropic API
key configured on WhatsApp Settings before it does anything.
""",
    "author": "Tsela NavTech",
    "license": "LGPL-3",
    "depends": ["contact_centre"],
    "data": [
        "data/ir_cron_data.xml",
        "views/whatsapp_config_views.xml",
        "views/contact_centre_contact_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": False,
}
